### ISSUE TITLE
Generation failed. replace() argument 1 must be str, not PosixPath

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/nunaweb#25] opened 2021-06-10 21:26 UTC
If you generate code for https://github.com/Zubax/zubax_dsdl by pasting the URL into the form, you get this:

<img width="360" alt="image" src="https://user-images.githubusercontent.com/3298404/121599392-a4bade00-ca4b-11eb-9390-518fb51669fa.png">

**Comment by bbworld1** [comment] 2021-06-12 06:49
Sorry I didn't catch this earlier, it was a simple formatting type error.

What's interesting is after fixing the bug, there was still an issue, but it appears to be with the repo itself. PyDSDL complains about zubax_internet conflicting with zubax because they both start with zubax: https://github.com/UAVCAN/pydsdl/blob/cee519f73effbec45570cd4bce50d4625b9ac7c2/pydsdl/_namespace.py#L404

The issue is fixed in PR #28 .

**Comment by pavel-kirienko** [comment] 2021-06-12 19:59
I don't think the zubax_dsdl repo is at fault, otherwise this wouldn't pass: https://github.com/Zubax/zubax_dsdl/blob/7f9ccf19409354cc88c1c5b03d65db874fd2051d/.travis.yml#L10

**Comment by bbworld1** [comment] 2021-06-12 20:37
I think this has to do with how nunaweb handles linking namespaces against each other. Because nunaweb links all namespaces found against each other, it tries to link zubax_internet as a lookup namespace to zubax, which causes the error. The reason the error isn't thrown by the CI check linked is because it compiles the workspaces separately.

I think this issue would be difficult to solve without fundamentally changing how nunaweb handles linking lookup namespaces. The question is whether this is intended behavior or not; if it's not, do you have any proposals on how to resolve this?

**Comment by pavel-kirienko** [comment] 2021-06-12 22:14
Sorry, it was a bug in PyDSDL. [Fixed in v1.12.1](https://github.com/UAVCAN/pydsdl/commit/7d93f00158d2145a2997c37fc16710ae291220a6); please, bump the dependency version.

**Closed as completed** 2021-06-15 00:33 UTC
Labels: bug
